name: restaurant
description: Restaurant module.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

  common:
    path: ../common
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.10
  build_runner:

flutter:
